spring:
  application:
    name: goaps
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/auth_db}
    username: ${DATABASE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${DATABASE_PASSWORD:${POSTGRES_PASSWORD:yourpassword}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.goaps.config: DEBUG

server:
  port: ${PORT:8080}
